FROM registry.access.redhat.com/ubi9/ubi

RUN yum install -y python3 python3-pip git && yum clean all

WORKDIR /app
COPY requirements.txt /app/
RUN python3 -m pip install -r requirements.txt
RUN curl -LO https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Linux-x86_64.sh
RUN bash Miniconda3-py310_23.3.1-0-Linux-x86_64.sh -b -f
RUN curl https://pyenv.run | bash
RUN export PYENV_ROOT="$HOME/.pyenv" && command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH" && eval "$(pyenv init -)"
